import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readSaved,remember,writeSaved} from '../src/storage.ts';
import {parseInput,type Receipt} from '../src/engine.ts';
const r:Receipt={id:'test',date:new Date().toISOString(),input:'喝咖啡',style:'gentle',items:parseInput('喝咖啡')};
test('只保留20张并按ID更新已有记录',()=>{let history:Receipt[]=[];for(let i=0;i<25;i++)history=remember(history,{...r,id:`id-${i}`});assert.equal(history.length,20);assert.equal(history[0].id,'id-24');assert.equal(history[19].id,'id-5');history=remember(history,{...history[4],style:'snark'});assert.equal(history.length,20);assert.equal(history[0].style,'snark');});
test('本地内容往返恢复与异常处理',()=>{let data:string|null=null;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>data,setItem:(_key:string,value:string)=>{data=value;}}});writeSaved({history:[r],draft:'草稿',current:r});assert.deepEqual(readSaved().data,{history:[r],draft:'草稿',current:r});data='{bad';assert.match(readSaved().warning,/不自动写入/);assert.equal(data,'{bad');data=JSON.stringify({history:[{...r,items:[{...r.items[0],quantity:-99}]}],draft:''});assert.ok(readSaved().warning);Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>{throw Error('denied')},setItem:()=>{throw Error('quota')}}});assert.ok(readSaved().warning);assert.throws(()=>writeSaved({history:[],draft:''}));});
test('更多异常负载整体拒绝，且不清空原记录',()=>{let data:string|null=null;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>data,setItem:(_key:string,value:string)=>{data=value;}}});
  const bad:unknown[]=[{history:[{...r,items:[]}],draft:''},{history:[{...r,items:Array(31).fill(r.items[0])}],draft:''},{history:[{...r,items:[{...r.items[0],unit:101}]}],draft:''},{history:[{...r,items:[{...r.items[0],quantity:0}]}],draft:''},{history:[JSON.parse(JSON.stringify({...r,style:'rude'}))],draft:''},{history:'nope',draft:''},{history:[r],draft:'字'.repeat(2001)},{history:[r],draft:'',current:{...r,date:'不是日期'}},{history:[JSON.parse(JSON.stringify({...r,items:[{...r.items[0],variant:3}]}))],draft:''}];
  for(const c of bad){data=JSON.stringify(c);const res=readSaved();assert.ok(res.warning,'应提示无法读取');assert.deepEqual(res.data,{history:[],draft:''});assert.equal(data,JSON.stringify(c),'原记录不被覆盖');}});
test('历史超过20张时读取截断到20张',()=>{const many=Array.from({length:25},(_,i)=>({...r,id:`h-${i}`}));let data:string|null=JSON.stringify({history:many,draft:''});Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>data,setItem:(_key:string,value:string)=>{data=value;}}});const res=readSaved();assert.equal(res.warning,'');assert.equal(res.data.history.length,20);assert.equal(res.data.history[0].id,'h-0');});

test('带文案变体的小票可往返恢复',()=>{let data:string|null=null;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>data,setItem:(_key:string,value:string)=>{data=value;}}});const v:Receipt={...r,items:[{...r.items[0],variant:1}]};writeSaved({history:[v],draft:'',current:v});assert.deepEqual(readSaved().data.current,v);});
