import { useEffect, useRef, useState } from 'react';
import { ReceiptText, History as HistoryIcon, Printer, ArrowRight, PencilLine, Download, LockKeyhole, Smile, Sparkles, Orbit, BriefcaseBusiness, Sofa, Heart, Check } from 'lucide-react';
import { createReceipt, examples, sampleReceipt, styles, type Receipt, type Style } from './engine';
import { readSaved, remember, writeSaved } from './storage';
import ReceiptPaper from './ReceiptPaper';
import { Editor, History } from './Dialogs';
export default function App(){
  const [loaded]=useState(readSaved);
  const [input,setInput]=useState(loaded.data.draft);
  const [receipt,setReceipt]=useState<Receipt>(()=>loaded.data.current || sampleReceipt());
  const [style,setStyle]=useState<Style>(loaded.data.current?.style || 'gentle');
  const [history,setHistory]=useState(loaded.data.history);
  const [warning,setWarning]=useState(loaded.warning);
  const [error,setError]=useState('');const [status,setStatus]=useState('');
  const [printing,setPrinting]=useState(false);const [exporting,setExporting]=useState(false);
  const [dialog,setDialog]=useState<'edit'|'history'|null>(null);const [printKey,setPrintKey]=useState(0);
  const lock=useRef(false);const exportLock=useRef(false);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const inputRef=useRef<HTMLTextAreaElement>(null);
  const userChanged=useRef(false);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  useEffect(()=>{if(!userChanged.current || loaded.warning)return;try{writeSaved({history,draft:input,current:receipt});setWarning('');}catch{setWarning('本地保存失败（空间不足或存储被禁用）。当前小票仍可导出 PNG，刷新可能丢失。');}},[history,input,receipt,loaded.warning]);
  useEffect(()=>{if(!status)return;const id=setTimeout(()=>setStatus(''),4000);return()=>clearTimeout(id);},[status]);
  const commit=(next:Receipt,animate=true)=>{userChanged.current=true;setReceipt(next);if(!next.example)setHistory(prev=>remember(prev,next));if(animate){lock.current=true;setPrinting(true);setPrintKey(k=>k+1);clearTimeout(timer.current);timer.current=setTimeout(()=>{lock.current=false;setPrinting(false);setStatus('今日已结算，小票请收好。');},window.matchMedia('(prefers-reduced-motion: reduce)').matches?10:1800);}};
  const generate=()=>{if(lock.current)return;try{const next=createReceipt(input,style);setError('');commit(next);}catch(e){setError(e instanceof Error?e.message:'没能结算，请再试一次。');inputRef.current?.focus();}};
  const chooseStyle=(next:Style)=>{if(lock.current)return;setStyle(next);commit({...receipt,style:next},false);};
  const savePng=async()=>{if(exportLock.current||lock.current)return;exportLock.current=true;setExporting(true);setError('');try{const {exportPng}=await import('./exportPng');await exportPng(receipt);setStatus('PNG 已生成，请查看浏览器下载。');}catch{setError('图片导出失败，请重试，或使用截图保存；你的小票还在。');}finally{exportLock.current=false;setExporting(false);}};
  return <div className="app-shell"><header className="site-header"><a className="brand" href="./"><ReceiptText size={27}/><span>人生离谱小票机</span></a><button className="history-button" onClick={()=>setDialog('history')}><HistoryIcon size={19}/>最近小票{history.length>0&&<span className="history-count">{history.length}</span>}</button></header>
    <main><section className="input-side"><div className="intro"><h1>把今天的离谱，<br/><em>打成一张小票。</em></h1><p>快乐可以入账，内耗也有明细。<br/>这里不算钱，只算你的精神电量。</p></div><form onSubmit={e=>{e.preventDefault();generate();}}><div className="section-label"><span>01</span><label htmlFor="day-input">今天都经历了什么？</label></div><div className="examples">{examples.map((example,index)=>{const Icon=[BriefcaseBusiness,Smile,Sofa][index];return <button key={example.name} type="button" disabled={printing} onClick={()=>{userChanged.current=true;setInput(example.text);setError('');inputRef.current?.focus();}}><Icon size={16}/>{example.name}</button>;})}</div><div className="textarea-wrap"><textarea id="day-input" ref={inputRef} value={input} maxLength={2000} disabled={printing} placeholder={'比如：开了3场会议；喝了1杯咖啡；\n挤地铁回家；看到了下班晚霞\n\n一行一件小事，也可以用分号分开。'} onChange={e=>{userChanged.current=true;setInput(e.target.value);setError('');}} aria-describedby="input-help input-error"/><div className="textarea-bottom"><span id="input-help">每行一件 · 最多 30 件</span><span>{input.length} / 2000 字</span></div></div><fieldset className="style-field"><legend>选择你的收银员语气</legend><div className="style-options">{styles.map((s,index)=>{const Icon=[Smile,Sparkles,Orbit][index];return <button type="button" key={s.id} aria-pressed={style===s.id} className={style===s.id?'selected':''} disabled={printing} onClick={()=>chooseStyle(s.id)}><Icon size={19}/>{s.name}</button>;})}</div><p className="style-hint">{styles.find(s=>s.id===style)?.hint}</p></fieldset><button className="primary settle" disabled={printing} type="submit"><Printer size={24}/>{printing?'正在打印今天…':'结算今天'}<ArrowRight size={21}/></button><p className="local-note"><LockKeyhole size={13}/>本地趣味生成 · 你的日常，只留在这台设备</p></form><div id="input-error" role="alert" className={error?'notice error':''}>{error}</div>{warning&&<p className="notice" role="alert">{warning}</p>}</section>
    <section className={`output-side ${printing?'printing':''}`} aria-label="小票打印机" aria-busy={printing}><div className="printer"><div className="printer-top"><span className="ready"><i/>{printing?'PRINTING':'READY'}</span><span className="printer-name">TODAY MART</span><div className="vents"><i/><i/><i/><i/></div><button className="feed-button" aria-label="再次打印今天" title="再次打印今天" disabled={printing} onClick={generate}><Printer size={20}/></button></div><div className="paper-slot"/><div className="printer-lower"/></div><div className="paper-path"><div key={printKey} className={printing?'paper-motion animate-print':'paper-motion'}><ReceiptPaper receipt={receipt}/></div></div><div className="receipt-actions"><button disabled={printing||exporting} onClick={()=>setDialog('edit')}><PencilLine size={18}/>修改明细</button><button disabled={printing||exporting} onClick={savePng}><Download size={18}/>{exporting?'正在保存…':'保存 PNG'}</button></div><p className="output-note">{receipt.example?'先看看这张示例，你的今天会是什么样？':'电量可以为负，也可以溢出。生活不用卡在 100 分。'}</p></section></main>
    <footer><Heart size={16}/><span>今天辛苦了，小票请收好。</span></footer>{status&&<div className="toast" role="status"><Check size={17}/>{status}</div>}{dialog==='edit'&&<Editor receipt={receipt} onClose={()=>setDialog(null)} onSave={items=>{setDialog(null);commit({...receipt,example:false,items});}}/>}{dialog==='history'&&<History receipts={history} onClose={()=>setDialog(null)} onRestore={next=>{if(lock.current)return;setInput(next.input);setStyle(next.style);setDialog(null);setError('');commit(next);}}/>}</div>;
}

