import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Plus, X, Trash2, ArrowUpRight } from 'lucide-react';
import { formatDate, itemName, styles, totals, type Item, type Receipt } from './engine';
export function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current!;const focused=document.activeElement as HTMLElement|null;dialog.showModal();document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow='';focused?.focus();};},[]);
  return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const box=e.currentTarget.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)onClose();}}} aria-label={title}><div className="dialog-header"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="关闭"><X size={22}/></button></div>{children}</dialog>;
}
export function Editor({receipt,onSave,onClose}:{receipt:Receipt;onSave:(items:Item[])=>void;onClose:()=>void}){
  const [items,setItems]=useState(()=>receipt.items.map(i=>({...i,customName:itemName(i,receipt.style)})));
  const update=(id:string,change:Partial<Item>)=>setItems(prev=>prev.map(i=>i.id===id?{...i,...change}:i));
  return <Dialog title="这笔账，你说了算" onClose={onClose}><p className="dialog-intro">修改名称、数量与单件电量，再重新结算。原始事件保留供核对。</p><form onSubmit={e=>{e.preventDefault();onSave(items.map(i=>{const previous=receipt.items.find(p=>p.id===i.id);const name=i.customName?.trim();return {...i,customName:previous && name===itemName(previous,receipt.style)?previous.customName:name};}));}}><div className="edit-list">{items.map((item,index)=><div className="edit-row" key={item.id}><div className="edit-name"><label htmlFor={`name-${item.id}`}>商品 {index+1}</label><input id={`name-${item.id}`} value={item.customName} maxLength={200} required pattern=".*\S.*" onChange={e=>update(item.id,{customName:e.target.value})}/><small>原话：{item.raw}</small></div><div className="edit-numbers"><label>数量<input aria-label={`数量 ${index+1}`} type="number" min="1" max="99" step="1" required value={Number.isNaN(item.quantity)?'':item.quantity} onChange={e=>update(item.id,{quantity:e.target.valueAsNumber})}/></label><label>单件电量<input aria-label={`单件电量 ${index+1}`} type="number" min="-100" max="100" step="1" required value={Number.isNaN(item.unit)?'':item.unit} onChange={e=>update(item.id,{unit:e.target.valueAsNumber})}/></label><button type="button" className="icon-btn remove" disabled={items.length===1} aria-label={`移除商品 ${index+1}`} onClick={()=>setItems(items.filter(i=>i.id!==item.id))}><Trash2 size={18}/></button></div></div>)}</div><button className="add-row" type="button" disabled={items.length>=30} onClick={()=>setItems([...items,{id:crypto.randomUUID(),raw:'手动添加',rule:'unknown',customName:'自己定义的小事',quantity:1,unit:0}])}><Plus size={16}/>添一件小事</button><div className="editor-footer"><span>结算余额 <b>{Number.isFinite(totals(items).balance)?totals(items).balance:'—'}</b></span><button type="submit" className="primary compact">重新结算</button></div><p className="fineprint">数量 1–99，单件电量 -100–100；修改后的名称在切换语气时保留。</p></form></Dialog>;
}
export function History({receipts,onRestore,onClose}:{receipts:Receipt[];onRestore:(r:Receipt)=>void;onClose:()=>void}){
  return <Dialog title="最近的小票" onClose={onClose}><p className="dialog-intro">最近 20 张，替你记着。仅保存在当前浏览器。</p>{receipts.length?<div className="history-list">{receipts.map(r=><button className="history-row" key={r.id} onClick={()=>onRestore(r)}><div><small>{formatDate(r.date)} · {styles.find(s=>s.id===r.style)?.name}</small><strong>{itemName(r.items[0],r.style)}{r.items.length>1?` 等 ${r.items.length} 件小事`:''}</strong><span>{r.id}</span></div><b>{totals(r.items).balance}</b><ArrowUpRight size={20}/></button>)}</div>:<div className="history-empty">还没有正式结算的小票。<p>把今天的小事写下来，第一张就有了。</p></div>}</Dialog>;
}

